name: Labeler
on:
  pull_request:
    branches:
    - master

jobs:
  label:

    runs-on: macOS-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
